version: '3'

services:
  chrome-bot:
    build: .
    container_name: chrome-bot
    ports:
      - "5900:5900"
    volumes:
      - chrome-data:/home/chrome
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    restart: always

volumes:
  chrome-data:
