services:
  chrome-bot:
    build: .
    container_name: chrome-bot
    ports:
      - "5900:5900"
    volumes:
      - chrome-data:/root/.config/google-chrome
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    restart: always

volumes:
  chrome-data:
